Add validate-db-reset.jenkinsfile
Fantom-foundation/LaScala pull request #133
Opened 2024-09-10 07:29 UTC by cabrador

This PR adds `validate-db-reset.jenkinsfile` which tests the `reset` feature in

2024-09-10 08:07 UTC, kjezek requested changes
Please use a "standard" way of checkout and build of Aida+Carmen, it makes sure a compatible composite is tested. 

```

        stage('Checkout') {
            steps {
                script {
                    currentBuild.description = "Building on ${env.NODE_NAME}"
                }

                checkout scmGit(
                    branches: [[name: "${AidaVersion}"]],
                    userRemoteConfigs: [[
                        url: 'https://github.com/Fantom-foundation/Aida.git'
                    ]]
                )
                sh "git submodule update --init --recursive"

                dir('carmen') {
                    checkout scmGit(
                        branches: [[name: "${CarmenVersion}"]],
                        userRemoteConfigs: [[url: 'https://github.com/Fantom-foundation/Carmen.git']]
                    )
                }
            }
        }

        stage('Build') {
            steps {
                sh "go mod tidy"
                sh "make -j aida-vm-sdb"
                sh 'go test ./...'
            }
        }

```

2024-09-10 19:24 UTC, Lubomir-Jahn approved these changes
Just please fix the formatting. Looks good otherwise 👍🏻

2024-09-10 19:24 UTC, Lubomir-Jahn commented on carmen/validate-db-reset.jenkinsfile
> +	    TMPDB = '/mnt/tmp-disk'
nit: formatting
```suggestion
        TMPDB = '/mnt/tmp-disk'
```

2024-09-12 14:54 UTC, kjezek requested changes
It looks good to me, just the pipeline seems to manipulate files that are never created by this pipeline - I guess copy+paste error. It should be cleared up, not to confuse the reader.

2024-09-12 15:04 UTC, Lubomir-Jahn commented on carmen/validate-db-reset.jenkinsfile
> +                sh "rm -f *.cpuprofile *.memprofile *.log"
Good point. These files are really not produced by this pipeline and this line should be removed.
```suggestion
```

2024-09-13 11:27 UTC, kjezek requested changes
General feedback first:
after previous round of review, the pipeline was basically ready. For a next review round, the way the pipeline works is widely changed. This makes review process and generally path to the final solution very difficult. The review should lead step-by-step to the final version, but when a step is complete rework, it can hardly lead to a quick resolution of the task.

Now to the pipeline: it executes 3 times exactly the same code. I am not fan of this approach. What if we want to scale this pipeline from 0 to N, do we want to end-up changing the pipeline every time?

What if we have just the simple pipeline with one job as it was previously and only plan as many jobs as we want in parallel? Lets say this job takes one hour, we can then schedule this job to start every 20minutes, and we would reach the same scaling. Of course, we can modify this as frequently as we like.

2024-09-13 13:16 UTC, kjezek approved these changes
much more elegant, thanks

2024-09-13 13:20 UTC, merged