introduces pipeline to test toolbox that initializes archive from live db
Fantom-foundation/LaScala pull request #141
Opened 2024-09-16 15:44 UTC by kjezek

This PR introduces pipeline to test toolbox that initializes archive from live db

2024-09-17 14:55 UTC, Lubomir-Jahn requested changes

2024-09-17 14:55 UTC, Lubomir-Jahn commented on carmen/validate-state-toolchain-init-archive.jenkinsfile
> +        string(name: 'aidaDb', defaultValue: '/mnt/aida-db-central/aida-db', description: 'Temporary directory to read Aida DB from.')
I would suggest to convert these parameters into environment variables since they will probably never change.

2024-09-18 11:10 UTC, kjezek commented on carmen/validate-state-toolchain-init-archive.jenkinsfile
> +        string(name: 'aidaDb', defaultValue: '/mnt/aida-db-central/aida-db', description: 'Temporary directory to read Aida DB from.')
ok, updated

2024-09-18 15:10 UTC, Lubomir-Jahn approved these changes

2024-09-19 06:09 UTC, merged