Add geth Sonic tests
Fantom-foundation/LaScala pull request #170
Opened 2024-10-16 14:40 UTC by cabrador

This PR adds jenkinsfile which executes `aida geth-tests` upon all combination of `LFVM/GethVM`, `CarmenDB/GethDB`.
It also creates a directory `sonic` for pipelines regarding the client.

2024-10-16 15:50 UTC, kjezek requested changes
I think ethereum tests should also use the `checkout scmGit( ... )` construct as for other checkouts in this pipeline. 

Otherwise it looks good, thanks for this contribution.

2024-10-16 15:50 UTC, kjezek commented on sonic/geth-state-tests.jenkinsfile
> +                    sh "rm -rf ${env.WORKSPACE}/eth-test-package/tests"
why does it need to clean the directory before?

I think it should use the  `checkout scmGit( ... )` construct as for other checkouts. It makes sure the right version is checked out, and overrides all possible leftovers.

2024-10-17 07:02 UTC, cabrador commented on sonic/geth-state-tests.jenkinsfile
> +                    sh "rm -rf ${env.WORKSPACE}/eth-test-package/tests"
good point.

2024-10-17 08:31 UTC, LuisPH3 requested changes
I have a question:
- How long does each one of the steps take to execute? 
In addition, I have some comments

2024-10-17 08:31 UTC, LuisPH3 commented on sonic/geth-state-tests.jenkinsfile
> +        string(defaultValue: 'main', description: 'Can be either branch name or commit hash.', name: 'ToscaVersion')
please write name as first argument

2024-10-17 08:31 UTC, LuisPH3 commented on sonic/geth-state-tests.jenkinsfile
> +                sh "git submodule update --init --recursive"
nit: add `--depth 1` would prevent full clone of submodule repositories and would speed up download

2024-10-17 08:31 UTC, LuisPH3 commented on sonic/geth-state-tests.jenkinsfile
> +                sh "make -j aida-vm-sdb"
note: -j without arguments is quite dangerous because it will spawn as many parallel jobs as tasks available in the make script (independent of available cores), in case of a C++ project this would immediately consume all available memory.
This is an antipattern, and I can see that it is used inside of Aida Makefiles as well.

2024-10-17 08:31 UTC, LuisPH3 commented on sonic/geth-state-tests.jenkinsfile
> +                        sh "./build/aida-vm-sdb ethereum-test --db-impl carmen --carmen-schema 5 --validate --evm-impl ethereum --vm-impl geth --db-tmp  ${params.tmpDb} ${env.WORKSPACE}/eth-test-pack
tmpDb is not a parameter but environment. 
Jenkins accepts this somehow, but could stop working after an update.

2024-10-17 08:31 UTC, LuisPH3 commented on sonic/geth-state-tests.jenkinsfile
> +            parallel {
nodes with label agent  'x86-4-32-s'  have only one executor. This parallel section will have to run sequentially because the whole pipeline runs in the agent defined in the top level.

Option A)  
To achieve parallel execution, the top level could be assigned to a coordinator and each stage inside the parallel region needs its own agent declaration.

(note that build would have to be moved into each parallel section as well, because it would be another machine) 
This could be pretty expensive in VM cost. 

Option B) 
assign more executors to each instance of 'x86-4-32-s'. This would start doing parallel work, but It would most problably run into resources problems and or filesystem clashes. all tests will be executing simultaneusly in the same machine, using the same tmpDb

option C) 
Delete superfulous parallel refactor pipeline to accept flavor as parameter, keep 1 code, and schedule 4 jenkins jobs for each of the flavors.

2024-10-17 11:07 UTC, kjezek commented on sonic/geth-state-tests.jenkinsfile
> +                stage('CarmenDB+GethVM') {
rejecting a recommendation without any comment is not nice

2024-10-17 11:07 UTC, kjezek commented on sonic/geth-state-tests.jenkinsfile
> +                stage('CarmenDB+LFVM') {
rejecting a recommendation without any comment is not nice

2024-10-17 11:11 UTC, kjezek commented on sonic/geth-state-tests.jenkinsfile
> +                stage('CarmenDB+LFVM') {
btw: I added this comment because `carmen` = `database` , i.e  carmenDB is tautology - like .e.g "LED diode", "LCD display", ....

2024-10-17 11:15 UTC, kjezek commented on sonic/geth-state-tests.jenkinsfile
> +            parallel {
good point Luise, I missed this.  Actually point C does not sound bad to me.  The argument about having a single commit to debug has IMHO a limited merit as we already have tens of pipelines that may potentially run different commits. Combination of A+B is what we do in other pipelines, i.e. perhaps the ideal solution in current setup

2024-10-17 11:22 UTC, cabrador commented on sonic/geth-state-tests.jenkinsfile
> +            parallel {
Right, I did not realize running in parallel does not work on one machine. Lets keep this sequential since this test is pretty low.

2024-10-17 11:23 UTC, cabrador commented on sonic/geth-state-tests.jenkinsfile
> +                        sh "./build/aida-vm-sdb ethereum-test --db-impl carmen --carmen-schema 5 --validate --evm-impl ethereum --vm-impl geth --db-tmp  ${params.tmpDb} ${env.WORKSPACE}/eth-test-pack
Fixed.

2024-10-17 11:24 UTC, cabrador commented on sonic/geth-state-tests.jenkinsfile
> +                sh "git submodule update --init --recursive"
do we really want that?

2024-10-17 12:24 UTC, LuisPH3 commented on sonic/geth-state-tests.jenkinsfile
> +                sh "git submodule update --init --recursive"
It is just a small optimization, nothing we really need.
(for CI pipelines on the other hand, I would like to have the fastest execution posible)

2024-10-17 12:24 UTC, LuisPH3 commented on sonic/geth-state-tests.jenkinsfile
> +                sh "make -j aida-vm-sdb"
please remove -j

2024-10-17 13:26 UTC, cabrador commented on sonic/geth-state-tests.jenkinsfile
> +                stage('CarmenDB+GethVM') {
wdym? I removed it

2024-10-17 14:18 UTC, LuisPH3 approved these changes
Much cleaner. 
Have you already run this pipeline as an experiment? A link to Jenkins would be useful for future PRs.

2024-10-17 14:25 UTC, kjezek commented on sonic/geth-state-tests.jenkinsfile
> +                stage('CarmenDB+GethVM') {
I have seen it resolved but not updated. Sorry if this was only a non-refreshed page or something similar

2024-10-18 16:08 UTC, kjezek approved these changes
Thanks, it looks good to me. 

I liked the previous version running in parallel as the stages in the pipeline are independent, i.e. not fully clear to me why it got removed, but ok.

2024-10-18 16:12 UTC, kjezek commented on sonic/geth-state-tests.jenkinsfile
> +            parallel {
well, it may work on the same machine if the machine is configured so - I think it is the point @LuisPH3 wanted to stress. I think the pipeline should not be designed based on current configuration. If the stages are independent it is IMHO natural to define them as `parallel` does not matter on which node they end-up being executed.

2024-10-21 09:52 UTC, cabrador commented
> Thanks, it looks good to me.
> 
> I liked the previous version running in parallel as the stages in the pipeline are independent, i.e. not fully clear to me why it got removed, but ok.

@kjezek As @LuisPH3 mentioned, we would need to spawn multiple workers for that and since the runtime is so low, I dont think its worth the additional resources usage.

2024-10-21 10:38 UTC, kjezek commented
> As @LuisPH3 mentioned, we would need to spawn multiple workers for that and since the runtime is so low, I dont think its worth the additional resources usage.

I must admit, I do not understand this comment. Are you talking about resources needed to run Jenkins stages? I think running N stages in sequence or in parallel consumes exactly the same amount of resources, is not it? 

My point was just there is a syntax in pipeline that says "these jobs are independent, and can run in parallel", and how much in parallel they run depends on available agents and the number of executers on each of them. I guess it is what @LuisPH3 meant as well. 

I approved, because I do not see the new version as incorrect, however, the previous version was correct as well, and IMHO semantically better, because it explicitly said there are independent steps. How it is utilised at the end is another story.

2024-10-21 10:53 UTC, Lubomir-Jahn requested changes
Looks good. Please fix these details ping me for approval.

2024-10-21 10:53 UTC, Lubomir-Jahn commented on sonic/geth-state-tests.jenkinsfile
> +        AIDADB = '/mnt/aida-db-central/aida-db'
```suggestion
```
Variable is not used anywhere.

2024-10-21 10:53 UTC, Lubomir-Jahn commented on sonic/geth-state-tests.jenkinsfile
> +	    TMPDB = '/mnt/tmp-disk'
```suggestion
        TMPDB = '/mnt/tmp-disk'
```
Nit: formatting

2024-10-21 10:53 UTC, Lubomir-Jahn commented on sonic/geth-state-tests.jenkinsfile
> +
```suggestion
```
Nit: formatting

2024-10-21 11:40 UTC, Lubomir-Jahn approved these changes

2024-10-21 12:10 UTC, merged