executes eth-tests for Sonic client
Fantom-foundation/LaScala pull request #178
Opened 2024-10-21 14:22 UTC by kjezek

This PR creates a pipeline to run ethereum tests agains Sonic

2024-10-22 15:22 UTC, Lubomir-Jahn requested changes

2024-10-22 15:22 UTC, Lubomir-Jahn commented on sonic/eth-tests.jenkinsfile
> +    }
```suggestion
```
`TMPDB` is not used anywhere and as it is the only variable in the environment block, let's get rid of it as whole.

2024-10-22 15:22 UTC, Lubomir-Jahn commented on sonic/eth-tests.jenkinsfile
> +                sh "go test ./tests -timeout 4h"
```suggestion
                sh "go test ./tests"  
```
Timeout for the command is the same value as for the whole pipeline. This is a bit redundant I'd say as the job will be killed sooner by jenkins every time because the preceding stage take some time too.

2024-10-23 07:12 UTC, kjezek commented on sonic/eth-tests.jenkinsfile
> +                sh "go test ./tests -timeout 4h"
I updated to 2hours. Removing the timeout would mean 10mins only and it is not enough for this this.

2024-10-23 15:30 UTC, Lubomir-Jahn commented on sonic/eth-tests.jenkinsfile
> +                sh "go test ./tests -timeout 4h"
Understood :)

2024-10-23 15:30 UTC, Lubomir-Jahn approved these changes

2024-10-23 15:31 UTC, merged