P01 Prototype
Fantom-foundation/LaScala pull request #196
Opened 2024-10-31 10:11 UTC by rpl-ffl

2024-10-31 12:46 UTC, Lubomir-Jahn requested changes

2024-10-31 12:46 UTC, Lubomir-Jahn commented on release_testing/operational_tests/P01.jenkinsfile
> +        booleanParam(defaultValue: false, description: 'If checked, C1 stage will be executed', name: 'enableC1')
Please format the parameters in this fashion. 
```
booleanParam(
    name: 'enableDynamic',
    defaultValue: true,
    description: 'If checked, dynamic stage will be executed'
)
```

2024-10-31 12:47 UTC, Lubomir-Jahn commented
Was this tested on jenkins already?

2024-10-31 13:16 UTC, rpl-ffl commented
> Was this tested on jenkins already?

Tested here: https://scala.fantom.network/job/ReleaseTesting/job/Experimental/job/P01/20/

2024-10-31 13:22 UTC, rpl-ffl commented on release_testing/operational_tests/P01.jenkinsfile
> +        booleanParam(defaultValue: false, description: 'If checked, C1 stage will be executed', name: 'enableC1')
Fixed here: https://github.com/Fantom-foundation/LaScala/pull/196/commits/a5374f64fddf1720f2b4dbae22c22850e0baf736

2024-10-31 13:26 UTC, rpl-ffl commented on release_testing/operational_tests/P01.jenkinsfile
> +		always {
`post.always` -> `post.failure`
Only upload artifacts when run fails.

2024-10-31 17:01 UTC, Lubomir-Jahn requested changes

2024-10-31 17:01 UTC, Lubomir-Jahn commented on release_testing/operational_tests/P01.jenkinsfile
> +	)
Convention suggested by Luis tells us that name of the parameter should be first. Could I ask you to do this additional change please? 🙏🏻 

Please do not forget all the other parameters.

2024-11-01 06:38 UTC, rpl-ffl commented on release_testing/operational_tests/P01.jenkinsfile
> +	)
BooleanParam rearranged. Name first. https://github.com/Fantom-foundation/LaScala/pull/196/commits/43813dd44f8aed1831b4c1ea1899e914586d9eec

2024-11-01 06:44 UTC, Lubomir-Jahn approved these changes

2024-11-01 06:48 UTC, merged