Add tosca tests
Fantom-foundation/LaScala pull request #85
Opened 2024-04-26 12:42 UTC by petr-hanzl

This PR adds tosca tests

2024-04-28 08:05 UTC, Lubomir-Jahn requested changes

2024-04-28 08:05 UTC, Lubomir-Jahn commented on tosca/validate-evmzero.jenkinsfile
> +                }
Do we know how much data will this store in the `/tmp`. Problem is that boot disk where `/tmp` is, has only 20GB of space and will run out of it pretty quickly causing whole job to fail and leaving the VM unusable.

2024-04-28 08:05 UTC, Lubomir-Jahn commented on tosca/validate-geth.jenkinsfile
> +                        credentialsId:  'AidaCI_PR',
```suggestion
```

2024-04-28 08:05 UTC, Lubomir-Jahn commented on tosca/validate-geth.jenkinsfile
> +                		userRemoteConfigs: [[credentialsId:  'AidaCI_PR', url: 'https://github.com/Fantom-foundation/Tosca.git']]
```suggestion
                		userRemoteConfigs: [[url: 'https://github.com/Fantom-foundation/Tosca.git']]
```

2024-04-28 08:05 UTC, Lubomir-Jahn commented on tosca/validate-lfvm-si.jenkinsfile
> +                        credentialsId:  'AidaCI_PR',
```suggestion
```

2024-04-28 08:05 UTC, Lubomir-Jahn commented on tosca/validate-lfvm-si.jenkinsfile
> +                		userRemoteConfigs: [[credentialsId:  'AidaCI_PR', url: 'https://github.com/Fantom-foundation/Tosca.git']]
```suggestion
                		userRemoteConfigs: [[url: 'https://github.com/Fantom-foundation/Tosca.git']]
```

2024-04-28 08:05 UTC, Lubomir-Jahn commented on tosca/validate-lfvm.jenkinsfile
> +                        credentialsId:  'AidaCI_PR',
```suggestion
```

2024-04-28 08:05 UTC, Lubomir-Jahn commented on tosca/validate-lfvm.jenkinsfile
> +                		userRemoteConfigs: [[credentialsId:  'AidaCI_PR', url: 'https://github.com/Fantom-foundation/Tosca.git']]
```suggestion
                		userRemoteConfigs: [[url: 'https://github.com/Fantom-foundation/Tosca.git']]
```

2024-04-28 08:06 UTC, Lubomir-Jahn commented
Thanks for your work! Can you please remove the credentials from the build stages?

2024-04-29 07:42 UTC, petr-hanzl commented on tosca/validate-evmzero.jenkinsfile
> +                }
This tool does not create any `StateDb` on disk. It works with one in memory.

2024-04-29 13:30 UTC, Lubomir-Jahn approved these changes

2024-04-30 10:15 UTC, Lubomir-Jahn approved these changes

2024-04-30 10:22 UTC, merged